# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projuser',
            name='shenfen',
            field=models.CharField(blank=True, max_length=50, verbose_name='身份'),
        ),
    ]
