# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-16 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171214_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('role', models.CharField(default='网络管理员', max_length=50, verbose_name='角色')),
            ],
            options={
                'verbose_name': '网站扩展用户',
            },
        ),
    ]
