# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_webuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webuser',
            options={'verbose_name': '用户验证'},
        ),
        migrations.RenameField(
            model_name='projuser',
            old_name='shenfen',
            new_name='role',
        ),
    ]
