# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_auto_20171208_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetail',
            old_name='event',
            new_name='event_id',
        ),
    ]
