# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_auto_20171208_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetail',
            name='connect_person',
        ),
        migrations.DeleteModel(
            name='EventDetail',
        ),
    ]
